#!/usr/bin/env bash

track_info="$(mpc status -f '%title%~%artist%' | sed -E 's/ +/ /g')"
track_info_lines="$(echo "$track_info" | wc -l | sed 's/ //g')"
if [ "$track_info_lines" -eq "1" ] ;then
    exit
fi

track_line1="$(echo "$track_info" | head -n 1)"
track_line2="$(echo "$track_info" | tail -n +2 | head -n 1)"

track_title="$(echo "$track_line1" | cut -d '~' -f 1)"
track_artist="$(echo "$track_line1" | cut -d '~' -f 2)"
track_playing="$(echo "$track_line2" | cut -d ' ' -f 1)"
track_time_elapsed="$(echo "$track_line2" | cut -d ' ' -f 3 | cut -d '/' -f 1)"
track_time_total="$(echo "$track_line2" | cut -d ' ' -f 3 | cut -d '/' -f 2)"

[ "$track_playing" = '[playing]' ] && play_status="▶ " || play_status="❚❚"

elapsed="$(to-msec "$track_time_elapsed")"
total="$(to-msec "$track_time_total")"
remaining="$((total-elapsed))"
track_time_remaining="$(from-msec $remaining)"

printf ' %s %s │ %s │ %s' "$play_status" \
                          "$track_time_remaining" \
                          "$(truncate-string 20 "$track_title")" \
                          "$(truncate-string 20 "$track_artist")"
