#! /bin/bash
set -e

if [ -z "$1" ]; then
  echo 'Please provide a source png image'
  exit 1
fi

if [ -z "$2" ]; then
  echo 'Please provide an output file name'
  exit 1
fi

TEMPDIR=$(mktemp -d) || exit 1
LOGFILE="$TEMPDIR/$(basename "$0").log"
ICONSET="$TEMPDIR/$(basename "$0").iconset"

trap 'if [ "$?" != 0 ]; then mv -f $LOGFILE error.log; fi' EXIT
mkdir -p "$ICONSET"

echo 'Building iconset...'
{
  sips -z 16 16     "$1" --out "$ICONSET/icon_16x16.png"
  sips -z 32 32     "$1" --out "$ICONSET/icon_16x16@2x.png"
  sips -z 32 32     "$1" --out "$ICONSET/icon_32x32.png"
  sips -z 64 64     "$1" --out "$ICONSET/icon_32x32@2x.png"
  sips -z 128 128   "$1" --out "$ICONSET/icon_128x128.png"
  sips -z 256 256   "$1" --out "$ICONSET/icon_128x128@2x.png"
  sips -z 256 256   "$1" --out "$ICONSET/icon_256x256.png"
  sips -z 512 512   "$1" --out "$ICONSET/icon_256x256@2x.png"
  sips -z 512 512   "$1" --out "$ICONSET/icon_512x512.png"
  sips -z 1024 1024 "$1" --out "$ICONSET/icon_512x512@2x.png"
} >> "$LOGFILE" 2>&1
echo 'Complete!'

echo "Building $2..."
{
  iconutil -c 'icns' "$ICONSET" -o "$2"
} >> "$LOGFILE" 2>&1
echo 'Complete!'
