#! /bin/bash
set -e

BREW_URL='https://raw.githubusercontent.com/Homebrew/install/master/install'
LOG_FILE='install.log'

installDependencies() {
  which brew > /dev/null || ruby -e "$(curl -fsSL $BREW_URL)"
  brew update
  brew upgrade

  brew tap caskroom/versions

  # Python3 installation might fail if this is set
  unset PYTHONPATH

  xargs brew install < brew-formulae.txt
  xargs brew cask install < brew-cask-formulae.txt

  # Install a recent ruby version
  eval "$(rbenv init -)"
  rbenv install -s 2.4.0
  rbenv global 2.4.0
  gem install bundler

  # Install an up-to-date node version
  . "$HOME/.nvm/nvm.sh"
  nvm install node

	# Kakoune is not in the brew registry right now
	# so needs to be installed separately
	brew install --HEAD \
		https://raw.githubusercontent.com/mawww/kakoune/master/contrib/kakoune.rb
}

stowConfiguration() {
  ls 'stow/' | xargs -n 1 stow -d 'stow/' -t "$HOME"
}

{
  while (( "$#" )); do
    case "$1" in
      'install') installDependencies;;
      'stow')    stowConfiguration;;
    esac
    shift
  done
} >> "$LOG_FILE" 2>&1
