#!/bin/bash
set -e

if [ "$#" -lt 1 ]; then
  exit 1
fi

cd "${2:-$HOME/audio}" 1>/dev/null 2>&1 || exit 1
youtube-dl \
	--add-metadata \
	--extract-audio \
	--output '%(title)s [%(id)s].%(ext)s' \
	"https://www.youtube.com/watch?v=$1"
