#!/bin/bash
set -e

find_opts=(
  \(
    -type l -or
    -type f
  \)
  -and
  \(
    -name '*.opus' -or
    -name '*.webm' -or
    -name '*.m4a'  -or
    -name '*.ogg'
  \)
)

fzf_opts=(
  --multi
  --cycle
  --reverse
  --bind 'alt-a:select-all,alt-d:deselect-all'
)

mpv_statusline='\e[0;33m${time-pos}\e[0m'
mpv_statusline+='/'
mpv_statusline+='\e[0;33m${duration}\e[0m'
mpv_statusline+=' \e[0;32m${percent-pos}%\e[0m'
mpv_statusline+='\n${filename}'
mpv_opts=(
  --msg-level 'all=no,statusline=status'
  --term-status-msg="$mpv_statusline"
  --input-ipc-server='/tmp/mpvsocket'
)

path=${1:-$HOME/audio}
tracks=$(find "$path" "${find_opts[@]}" | sed "s#$path/##")
while :; do
  chosen=$(fzf ${fzf_opts[@]} <<< "$tracks")
	clear
  echo "$chosen"
  IFS=$'\n'
  mpv ${mpv_opts[@]} $(sed -E "s#^#$path/#" <<< "$chosen")
  echo
done
