source "%val{config}/csharp.kak"
source "%val{config}/fzf.kak"
source "%val{config}/git.kak"
source "%val{config}/go.kak"
source "%val{config}/javascript.kak"

colorscheme simple

set global ui_options ncurses_assistant=cat

set global tabstop 2
set global indentwidth 2
set global aligntab false

map global insert <tab> '<a-;><gt>'

set global modelinefmt '%sh{
	modified=$([ $kak_modified = "true" ] && echo "+ ")
	left="$kak_bufname"
	right="$modified$kak_cursor_line:$kak_cursor_char_column "
	printf "%s" "$left"
  printf "%-$(($kak_window_width - ${#left} - ${#right} - 1))s"
	printf "%s" "$right"
}'

map global user b -docstring 'jump to buffer using fzf + tmux' :fzf-buffer<ret>
map global user f -docstring 'jump to file using fzf + tmux' :fzf-file<ret>
map global user l -docstring 'jump to line using fzf + tmux' :fzf-line<ret>
alias global jump nop
map global user s -docstring 'jump to symbol under cursor' :jump<ret>

def env -docstring 'load the local .kakenv file if present' %{%sh{
  [ -f .kakenv ] && echo 'source .kakenv'
}}
