#!/bin/bash

FZF_NO_COLORS=''
FZF_NO_COLORS+='fg:-1,fg+:-1,'
FZF_NO_COLORS+='bg:-1,bg+:-1,'
FZF_NO_COLORS+='hl:-1,hl+:-1,'
FZF_NO_COLORS+='info:-1,'
FZF_NO_COLORS+='prompt:-1,'
FZF_NO_COLORS+='pointer:-1,'
FZF_NO_COLORS+='marker:-1,'
FZF_NO_COLORS+='spinner:-1,'
FZF_NO_COLORS+='header:-1'

export FZF_DEFAULT_COLORS="$FZF_NO_COLORS,pointer:2,marker:2,prompt:2,hl:3,hl+:3"
export FZF_DEFAULT_COMMAND='ag -l -f --hidden --ignore=".git"'
export FZF_DEFAULT_OPTS="--ansi --no-bold --color=$FZF_DEFAULT_COLORS"

[ -f "$HOME/.fzf.bash" ] && . "$HOME/.fzf.bash"
