#!/bin/bash

export HISTCONTROL=ignoreboth # ignores dups and whitespace
export HISTIGNORE=clear:ls
export HISTSIZE=1000000
export HISTFILESIZE=1000000
export HISTTIMEFORMAT="%F %T " # show times next to history items

shopt -s histappend

bind '"\e[A":history-search-backward'
bind '"\e[B":history-search-forward'
